[package]
name = "sapper_macros"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
serde = "1.0.7"
serde_json = "1.0.2"
sapper = { git="https://github.com/sappworks/sapper" }
sapper_query = { git="https://github.com/sappworks/sapper_query" }
sapper_body = { git="https://github.com/sappworks/sapper_body" }
sapper_tmpl = { git="https://github.com/sappworks/sapper_tmpl" }

